import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        'brand-primary': "#101828",
        'brand-secondary': "#6941C6",
        'brand-tertiary': "#475467",
        'border-secondary': "#E4E7EC",
        'secondary': "#F9FAFB",
      },
      fontWeight: {
        regular: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      borderRadius: {
        xl: "0.75rem",
        '2xl': "1rem"
      },
      maxWidth: {
        xxs: "20rem",
        xs: "24rem",
        sm: "30rem",
        md: "35rem",
        lg: "40rem",
        xl: "48rem",
        "2xl": "64rem",
        "3xl": "80rem",
        "4xl": "90rem",
        "5xl": "100rem",
        "6xl": "120rem",
      },
      width: {
        xxs: "20rem",
        xs: "24rem",
        sm: "30rem",
        md: "35rem",
        lg: "40rem",
        xl: "48rem",
        "2xl": "64rem",
        "3xl": "80rem",
        "4xl": "90rem",
        "5xl": "100rem",
        "6xl": "120rem",
      },
      spacing: {
        none: "0rem",
        xxs: "0.125rem",
        xs: "0.25rem",
        sm: "0.374rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.5rem",
        "6xl": "3rem",
        "7xl": "4rem",
        "8xl": "5rem",
        "9xl": "6rem",
        "10xl": "8rem",
        "11xl": "10rem",
      },
    },
  },
  plugins: [],
};
export default config;
